spring:
  thymeleaf:
    cache: false
    mode: HTML

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  session:
    store-type: none

server:
  port: 9090

platform:
  frontend:
    mall-id: M01

kakao:
  key: 336ba526ed79179967d6baae806c66fa
  restkey: ce4dd4a15adfd391c88f730c049f12c4
  secret: PQdDnZxEXfl6iC298N2xr12WGoiTvFLf

naver:
  key: xbLexjx52A_pQD0sZgIP
  callback: http://m.localhost:8080/login/navercallback
  callback2: http://m.localhost:8080/my/page/info/navercallback

ecp:
  api:
    base-url: https://56avor8q0k.execute-api.ap-northeast-2.amazonaws.com/sct
    api-key: DEV

amore:
  api:
    base-url: https://cit-prv-api-ddev.amorepacific.com/

webdb:
  api:
    base-url: http://10.155.8.76:8319/

bluewave:
  fileupload:
    location:
      temp: C:\temp\upload\
  imageresize:
    imagemagick: false