ecp:
  api:
    base-url: https://56avor8q0k.execute-api.ap-northeast-2.amazonaws.com/sct
    api-key: DEV

amore:
  api:
    base-url: https://cit-prv-api-ddev.amorepacific.com/

webdb:
  api:
    base-url: http://10.155.8.76:8319/

spring:
  session:
    store-type: redis

  redis:
    host: dspddev-ecp-cache.yo9wpv.ng.0001.apn2.cache.amazonaws.com

bluewave:
  fileupload:
    location:
      temp: /data/was/temp/upload
  imageresize:
    imagemagick: true