ecp:
  api:
    base-url: https://2g7rnnr513.execute-api.ap-northeast-2.amazonaws.com/ect_open
    api-key: A3Q0ACVQQ8DI5ABXX2LK88D6T4F9HBXV

amore:
  api:
    base-url: https://cit-prv-api-dstg.amorepacific.com/

webdb:
  api:
    base-url: http://10.155.8.76:8319/

spring:
  session:
    store-type: redis

  redis:
    host: dstg-rd-etd-cache.n7nudf.ng.0001.apn2.cache.amazonaws.com

#결제
payment:
  #inicis
  ini:
    mid: etudetest1
    keyPw: 1111
    signKey : bGRtZXBXZU11UWQ1R3RNY2FvN1NPZz09
    siteDomain :

    #이니시스 다이렉트 결제 - 카카오페이, 페이코결제
    direct:
      mid: etudetest0

  #네이버페이
  naver:
    clientId: u86j4ripEt8LRfPGzQ8
    mode: development

  #inicis 간편결제 (wpay)
  wpay:
    mid: etudepay00
    hashKey: F3149950A7B6289723F325833F588ETU
    seedKey: qn0d/tcu6EChPFfXDnU76Q==
    seedIv: WPAYETUDEPAY0000

  krp:
    mid: 2E673024B7
    secretKey: 44D3FA8EB70206CC4DCB7018984364B7

bluewave:
  fileupload:
    location:
      temp: /data/was/temp/upload
  imageresize:
    imagemagick: true