ecp:
  api:
    base-url: https://2g7rnnr513.execute-api.ap-northeast-2.amazonaws.com/ect_open
    api-key: A3Q0ACVQQ8DI5ABXX2LK88D6T4F9HBXV

amore:
  api:
    base-url: https://cit-prv-api-dstg.amorepacific.com/

webdb:
  api:
    base-url: http://10.155.8.76:8319/
    
pshop:
  api:
    base-url: https://pss-prv-api-dstg.amorepacific.com/

spring:
  session:
    store-type: redis
    redis:
      namespace: AMT

  redis:
    host: dstg-rd-session-01.n7nudf.ng.0001.apn2.cache.amazonaws.com
    port: 63791
    database: 2

#편의점택배
store:
  url:
    pc:
      base-url: https://ecp-stg.amorepacificmall.com
    mo:
      base-url: https://m-ecp-stg.amorepacificmall.com

#결제    
payment:
  #inicis 
  ini:
    inipayhome: /data/was/INIpay50
    mid: amoreTest1
    keyPw: 1111
    signKey: eUtWWWpkYWhIeGxUY2NPOVRQRFUrUT09
    pc:
      siteDomain: https://ecp-stg.amorepacificmall.com
    mo:
      siteDomain: https://m-ecp-stg.amorepacificmall.com
    # 이니시스 PC 결제 스크립트 import
    # 테스트 https://stgstdpay.inicis.com/stdjs/INIStdPay.js
    # 운영    https://stdpay.inicis.com/stdjs/INIStdPay.js
    # paymentJsUrl: https://stgstdpay.inicis.com/stdjs/INIStdPay.js
    
    #이니시스 다이렉트 결제 - 카카오페이, 페이코결제
    direct: 
      mid: amoreTest2
      signKey: Q1F3Q3N2a2RGYW5lbG0xQkVvQ2ZBdz09
  
  #네이버페이  
  naver:
    partnerId: amorepacific-mall
    clientId: HgNUQVYcJatk68lO2o0c
    clientSecret: MdwcNKybxY
    mode: development
    apiDomain: https://dev.apis.naver.com
    confirmUrl: /naverpay/payments/v2/apply/payment
    cancelUrl: /naverpay/payments/v1/cancel
  
  #inicis 간편결제 (wpay)  
  wpay:
    mid: INIWPAYTST
    hashKey: F3149950A7B6289723F325833F588STD
    seedKey: YXfk5YpaAlFPjFpczsB/yA==
    seedIv: WPAYINIWPAYTSTST

  krp:
    mid: 2E673024B7
    secretKey: 44D3FA8EB70206CC4DCB7018984364B7
    requestUrl: https://secureapi.test.eximbay.com/Gateway/BasicProcessor.krp
    #운영
    #requestUrl: https://secureapi.eximbay.com/Gateway/BasicProcessor.krp


bluewave:
  fileupload:
    location:
      temp: /data/was/temp/upload
  imageresize:
    imagemagick: true
    
    