spring:
  thymeleaf:
    cache: false
    mode: HTML
   
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  session:
    store-type: none
    redis:
      namespace: EMT

server:
  port: 8080

platform:
  frontend:
    mall-id: M02

#편의점택배
store:
  url:
    pc:
      base-url: http://localhost:8080
    mo:
      base-url: http://m.localhost:8080

#결제    
payment:
  #inicis 
  ini:
    inipayhome: C:\\INIpay50
    mid: etudetest1
    keyPw: 1111
    signKey: bGRtZXBXZU11UWQ1R3RNY2FvN1NPZz09
    pc:
      siteDomain: http://localhost:8080
    mo:
      siteDomain: http://m.localhost:8080
    # 이니시스 PC 결제 스크립트 import
    # 테스트 https://stgstdpay.inicis.com/stdjs/INIStdPay.js
    # 운영    https://stdpay.inicis.com/stdjs/INIStdPay.js
    # paymentJsUrl: https://stgstdpay.inicis.com/stdjs/INIStdPay.js
    
    #이니시스 다이렉트 결제 - 카카오페이, 페이코결제
    direct: 
      mid: etudetest0
      signKey: Q1F3Q3N2a2RGYW5lbG0xQkVvQ2ZBdz09
  
  #네이버페이  
  naver:
    partnerId: etude-shop
    clientId: iytyZfbZhrPBMOuunkqU
    clientSecret: epR8U0DeMy
    mode: development
    apiDomain: https://dev.apis.naver.com
    confirmUrl: /naverpay/payments/v2/apply/payment
    cancelUrl: /naverpay/payments/v1/cancel
  
  #inicis 간편결제 (wpay)  
  wpay:
    mid: INIWPAYTST
    hashKey: F3149950A7B6289723F325833F588STD
    seedKey: YXfk5YpaAlFPjFpczsB/yA==
    seedIv: WPAYINIWPAYTSTST
  
  krp:
    mid: 2E673024B7
    secretKey: 44D3FA8EB70206CC4DCB7018984364B7

kakao:
  key: 336ba526ed79179967d6baae806c66fa
  restkey: ce4dd4a15adfd391c88f730c049f12c4
  secret: PQdDnZxEXfl6iC298N2xr12WGoiTvFLf

naver:
  key: xbLexjx52A_pQD0sZgIP

facebook:
  key: 283723898436879

ecp:
  api:
    base-url: https://56avor8q0k.execute-api.ap-northeast-2.amazonaws.com/sct
    api-key: DEV
    # NONE, BASIC, HEADERS, FULL
    log-level: FULL

amore:
  api:
    base-url: https://cit-prv-api-ddev.amorepacific.com/

pos:
  api:
    base-url: https://epl-prv-api-ddev.amorepacific.com/

webdb:
  api:
    base-url: http://10.155.8.76:8319/

bluewave:
  fileupload:
    location:
      temp: C:\temp\upload\
  imageresize:
    imagemagick: false